'use client'

import { useState } from 'react';
import styles from '../styles/archives.module.scss';
import { fetchPlaylists } from '../lib/actions/archives';
import Episode from "../components/Episode";

// export const metadata: Metadata = {
//   title: "Archives Radio Paradis",
//   description: "Generated by create next app",
// };

export default async function Archives() {
  const playlists:any = fetchPlaylists();
  const [filteredPlaylistId, setFilteredPlaylistId] = useState('all');

  return (
    <div className={styles.archives}>
      <h1>Archives page</h1>
      {
        playlists.length > 0 ? (
          playlists.map((playlist: any) => (
            <div className={styles.episode} onClick={() => {
              setFilteredPlaylistId(playlist.id)
            }
            }>
              <h2>{playlist.title}</h2>
            </div>
          ))
        )
          :
          <div></div>
      }

      {
        playlists.length > 0 && filteredPlaylistId == 'all' ? (
          playlists.map((playlist: any) => (
            playlist.tracks.map((episode: any) => (
              <Episode key={episode.id} episode={episode} />
            ))
          ))
        )
          :
          playlists.length > 0 && filteredPlaylistId != 'all' ? (
            playlists
              .filter((playlist: any) => playlist.id.toString() === filteredPlaylistId)
              .map((playlist: any) => (
                playlist.tracks.map((episode: any) => (
                  <Episode key={episode.id} episode={episode} />
                ))
              ))
          )
            :
            <div></div>
      }
    </div>
  )
}
