import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Archives Radio Paradis",
  description: "Generated by create next app",
};


export default function Archives() {
  return <h1>Archives</h1>
}
