
import styles from '../styles/archives.module.scss';
import { fetchTracks } from '../lib/actions/archives';
import Archive from "../components/Archive";



// export const metadata: Metadata = {
//   title: "Archives Radio Paradis",
//   description: "Generated by create next app",
// };

export default async function Archives(props: any) {
  const tracks = await fetchTracks(100);

  return (
    <div className={styles.archives}>
       <Archive tracks={tracks}/>
    </div>
  )
}
